/**
 * FINAM Trade API Runtime Enums
 * Real enum objects available at runtime (not just type declarations)
 */

/**
 * Сторона сделки
 */
export enum Side {
  SIDE_UNSPECIFIED = 'SIDE_UNSPECIFIED',
  SIDE_BUY = 'SIDE_BUY',
  SIDE_SELL = 'SIDE_SELL',
}

/**
 * Тип заявки
 */
export enum OrderType {
  ORDER_TYPE_UNSPECIFIED = 'ORDER_TYPE_UNSPECIFIED',
  ORDER_TYPE_LIMIT = 'ORDER_TYPE_LIMIT',
  ORDER_TYPE_MARKET = 'ORDER_TYPE_MARKET',
  ORDER_TYPE_STOP = 'ORDER_TYPE_STOP',
  ORDER_TYPE_STOP_LIMIT = 'ORDER_TYPE_STOP_LIMIT',
}

/**
 * Время жизни заявки
 */
export enum TimeInForce {
  TIME_IN_FORCE_UNSPECIFIED = 'TIME_IN_FORCE_UNSPECIFIED',
  TIME_IN_FORCE_DAY = 'TIME_IN_FORCE_DAY',
  TIME_IN_FORCE_GTC = 'TIME_IN_FORCE_GTC',
  TIME_IN_FORCE_IOC = 'TIME_IN_FORCE_IOC',
  TIME_IN_FORCE_FOK = 'TIME_IN_FORCE_FOK',
}

/**
 * Статус заявки
 */
export enum OrderStatus {
  ORDER_STATUS_UNSPECIFIED = 'ORDER_STATUS_UNSPECIFIED',
  ORDER_STATUS_NEW = 'ORDER_STATUS_NEW',
  ORDER_STATUS_PARTIALLY_FILLED = 'ORDER_STATUS_PARTIALLY_FILLED',
  ORDER_STATUS_FILLED = 'ORDER_STATUS_FILLED',
  ORDER_STATUS_CANCELED = 'ORDER_STATUS_CANCELED',
  ORDER_STATUS_REJECTED = 'ORDER_STATUS_REJECTED',
}

/**
 * Условие стоп-заявки
 */
export enum StopCondition {
  STOP_CONDITION_UNSPECIFIED = 'STOP_CONDITION_UNSPECIFIED',
  STOP_CONDITION_MORE = 'STOP_CONDITION_MORE',
  STOP_CONDITION_LESS = 'STOP_CONDITION_LESS',
}

/**
 * Уровень котировок для рыночных данных
 */
export enum QuoteLevel {
  QUOTE_LEVEL_UNSPECIFIED = 'QUOTE_LEVEL_UNSPECIFIED',
  QUOTE_LEVEL_LAST_PRICE = 'QUOTE_LEVEL_LAST_PRICE',
  QUOTE_LEVEL_BEST_BID_OFFER = 'QUOTE_LEVEL_BEST_BID_OFFER',
  QUOTE_LEVEL_DEPTH_OF_MARKET = 'QUOTE_LEVEL_DEPTH_OF_MARKET',
  QUOTE_LEVEL_DEPTH_OF_BOOK = 'QUOTE_LEVEL_DEPTH_OF_BOOK',
  QUOTE_LEVEL_ACCESS_FORBIDDEN = 'QUOTE_LEVEL_ACCESS_FORBIDDEN',
}

/**
 * Тип аккаунта
 */
export enum AccountType {
  ACCOUNT_TYPE_UNSPECIFIED = 'ACCOUNT_TYPE_UNSPECIFIED',
  SIMPLE = 'SIMPLE',
  UNION = 'UNION',
  IIA = 'IIA',
}

/**
 * Статус аккаунта
 */
export enum AccountStatus {
  ACCOUNT_STATUS_UNSPECIFIED = 'ACCOUNT_STATUS_UNSPECIFIED',
  ACCOUNT_ACTIVE = 'ACCOUNT_ACTIVE',
  ACCOUNT_CLOSED = 'ACCOUNT_CLOSED',
}

/**
 * Тип инструмента
 */
export enum AssetType {
  TYPE_UNSPECIFIED = 'TYPE_UNSPECIFIED',
  EQUITIES = 'EQUITIES',
  FUTURES = 'FUTURES',
  OPTIONS = 'OPTIONS',
  BONDS = 'BONDS',
  CURRENCIES = 'CURRENCIES',
  INDICES = 'INDICES',
  ETF = 'ETF',
}

/**
 * Тип опциона
 */
export enum OptionType {
  TYPE_UNSPECIFIED = 'TYPE_UNSPECIFIED',
  TYPE_CALL = 'TYPE_CALL',
  TYPE_PUT = 'TYPE_PUT',
}

/**
 * Тип торговой сессии
 */
export enum SessionType {
  SESSION_TYPE_UNSPECIFIED = 'SESSION_TYPE_UNSPECIFIED',
  CLOSED = 'CLOSED',
  PRE_TRADING = 'PRE_TRADING',
  EARLY_TRADING = 'EARLY_TRADING',
  CORE_TRADING = 'CORE_TRADING',
  LATE_TRADING = 'LATE_TRADING',
  POST_TRADING = 'POST_TRADING',
}

/**
 * Временной интервал для баров
 */
export enum TimeFrame {
  TIME_FRAME_UNSPECIFIED = 'TIME_FRAME_UNSPECIFIED',
  TIME_FRAME_M1 = 'TIME_FRAME_M1',
  TIME_FRAME_M5 = 'TIME_FRAME_M5',
  TIME_FRAME_M15 = 'TIME_FRAME_M15',
  TIME_FRAME_M30 = 'TIME_FRAME_M30',
  TIME_FRAME_H1 = 'TIME_FRAME_H1',
  TIME_FRAME_H4 = 'TIME_FRAME_H4',
  TIME_FRAME_D = 'TIME_FRAME_D',
  TIME_FRAME_W = 'TIME_FRAME_W',
  TIME_FRAME_MN = 'TIME_FRAME_MN',
}

/**
 * Категория транзакции
 */
export enum TransactionCategory {
  TRANSACTION_CATEGORY_UNSPECIFIED = 'TRANSACTION_CATEGORY_UNSPECIFIED',
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  COMMISSION = 'COMMISSION',
  DIVIDEND = 'DIVIDEND',
  TRADE = 'TRADE',
  OTHER = 'OTHER',
}

/**
 * Действие в стакане
 */
export enum OrderBookAction {
  ACTION_UNSPECIFIED = 'ACTION_UNSPECIFIED',
  ACTION_ADD = 'ACTION_ADD',
  ACTION_UPDATE = 'ACTION_UPDATE',
  ACTION_DELETE = 'ACTION_DELETE',
}